import type { Locale } from '@/lib/i18n-context'

const ACTIVITY_PREFIXES_ZH: Array<[RegExp, string]> = [
    [/^(?:Check|Checking|Inspect|Inspecting|Review|Reviewing|Read|Reading|Explore|Exploring|Locate|Locating|Find|Finding)\s+/i, '正在检查：'],
    [/^(?:Search|Searching|Scan|Scanning|Query|Querying)\s+/i, '正在搜索：'],
    [/^(?:Diagnose|Diagnosing|Debug|Debugging|Investigate|Investigating|Trace|Tracing|Troubleshoot|Troubleshooting)\s+/i, '正在排查：'],
    [/^(?:Plan|Planning|Design|Designing|Outline|Outlining|Prepare|Preparing)\s+/i, '正在规划：'],
    [/^(?:Test|Testing|Verify|Verifying|Validate|Validating|Confirm|Confirming)\s+/i, '正在验证：'],
    [/^(?:Implement|Implementing|Add|Adding|Create|Creating)\s+/i, '正在实现：'],
    [/^(?:Build|Building)\s+/i, '正在构建：'],
    [/^(?:Generate|Generating|Render|Rendering)\s+/i, '正在生成：'],
    [/^(?:Update|Updating|Change|Changing|Adjust|Adjusting|Refactor|Refactoring|Simplify|Simplifying|Edit|Editing|Modify|Modifying|Apply|Applying|Patch|Patching|Write|Writing|Save|Saving)\s+/i, '正在修改：'],
    [/^(?:Fix|Fixing|Resolve|Resolving|Repair|Repairing)\s+/i, '正在修复：'],
    [/^(?:Run|Running|Execute|Executing|Invoke|Invoking|Call|Calling)\s+/i, '正在执行：'],
    [/^(?:Capture|Capturing|Take|Taking|Collect|Collecting|Gather|Gathering|Request|Requesting|Fetch|Fetching|Load|Loading|Extract|Extracting)\s+/i, '正在获取：'],
    [/^(?:Reload|Reloading|Refresh|Refreshing)\s+/i, '正在刷新：'],
    [/^(?:Select|Selecting|Choose|Choosing)\s+/i, '正在选择：'],
    [/^(?:Wait|Waiting|Poll|Polling|Monitor|Monitoring)\s+/i, '正在等待：'],
    [/^(?:Parse|Parsing|Analyze|Analyzing|Evaluate|Evaluating|Compare|Comparing|Assess|Assessing|Infer|Inferring)\s+/i, '正在分析：'],
    [/^(?:Translate|Translating|Localize|Localizing)\s+/i, '正在翻译：'],
    [/^(?:Summarize|Summarizing|Report|Reporting|Explain|Explaining|Document|Documenting)\s+/i, '正在总结：'],
    [/^(?:Deploy|Deploying|Publish|Publishing|Release|Releasing|Upload|Uploading|Sync|Syncing)\s+/i, '正在发布：'],
    [/^(?:Commit|Committing|Push|Pushing|Merge|Merging|Rebase|Rebasing)\s+/i, '正在提交：'],
    [/^(?:Install|Installing|Configure|Configuring|Set|Setting)\s+/i, '正在配置：'],
    [/^(?:Reproduce|Reproducing)\s+/i, '正在复现：'],
    [/^(?:Close|Closing|Open|Opening|Claim|Claiming|Handle|Handling|Process|Processing|Mark|Marking|Complete|Completing|Finish|Finishing|Finalize|Finalizing|Restore|Restoring|Resume|Resuming|Restart|Restarting|Start|Starting|Stop|Stopping)\s+/i, '正在处理：'],
]

const ACTIVITY_DETAIL_PHRASES_ZH: Array<[RegExp, string]> = [
    [/\bcurrent implementation\b/gi, '当前实现'],
    [/\bexisting implementation\b/gi, '现有实现'],
    [/\bcurrent state\b/gi, '当前状态'],
    [/\bsource code\b/gi, '源代码'],
    [/\bproject files?\b/gi, '项目文件'],
    [/\bworking tree\b/gi, '工作区'],
    [/\bfile changes?\b/gi, '文件改动'],
    [/\bcommit history\b/gi, '提交历史'],
    [/\bremote branch\b/gi, '远程分支'],
    [/\bgit status\b/gi, 'Git 状态'],
    [/\bexecution progress\b/gi, '执行进度'],
    [/\bprogress card\b/gi, '进度卡片'],
    [/\bprogress UI\b/gi, '进度界面'],
    [/\bstatus messages?\b/gi, '状态消息'],
    [/\bactivity titles?\b/gi, '操作标题'],
    [/\breasoning titles?\b/gi, '思考标题'],
    [/\bintermediate output\b/gi, '中间输出'],
    [/\blive output\b/gi, '实时输出'],
    [/\bcommand output\b/gi, '命令输出'],
    [/\bbuild output\b/gi, '构建输出'],
    [/\buser interface\b/gi, '用户界面'],
    [/\buser experience\b/gi, '用户体验'],
    [/\bmobile layout\b/gi, '移动端布局'],
    [/\bdesktop layout\b/gi, '桌面端布局'],
    [/\blocal storage\b/gi, '本地存储'],
    [/\bservice worker\b/gi, 'Service Worker'],
    [/\broot cause\b/gi, '根因'],
    [/\berror handling\b/gi, '错误处理'],
    [/\bsession state\b/gi, '会话状态'],
    [/\bresume flow\b/gi, '恢复流程'],
    [/\bdeployment status\b/gi, '部署状态'],
    [/\bproduction build\b/gi, '生产构建'],
    [/\bproduction deployment\b/gi, '生产部署'],
    [/\bvisual verification\b/gi, '视觉验收'],
    [/\bbrowser verification\b/gi, '浏览器验收'],
    [/\btest results?\b/gi, '测试结果'],
    [/\btest coverage\b/gi, '测试覆盖'],
    [/\btest suite\b/gi, '测试套件'],
    [/\btype checks?\b/gi, '类型检查'],
    [/\btype errors?\b/gi, '类型错误'],
    [/\bbuild errors?\b/gi, '构建错误'],
    [/\bnetwork requests?\b/gi, '网络请求'],
    [/\bAPI responses?\b/gi, 'API 响应'],
    [/\bHTTP responses?\b/gi, 'HTTP 响应'],
    [/\bauthentication flow\b/gi, '认证流程'],
    [/\bconversation history\b/gi, '会话历史'],
    [/\bmouse events?\b/gi, '鼠标事件'],
    [/\bevent dispatch\b/gi, '事件分发'],
    [/\bchild indexing\b/gi, '子项索引'],
    [/\btranslation rules?\b/gi, '翻译规则'],
    [/\bChinese translations?\b/gi, '中文翻译'],
    [/\bChinese localization\b/gi, '中文化'],
    [/\bevaluation card text\b/gi, '验收卡片文字'],
]

const ACTIVITY_DETAIL_WORDS_ZH: Readonly<Record<string, string>> = {
    a: '',
    an: '',
    the: '',
    and: '和',
    or: '或',
    with: '与',
    without: '不含',
    for: '用于',
    from: '来自',
    in: '中',
    inside: '内部',
    on: '上',
    of: '的',
    to: '到',
    before: '之前',
    after: '之后',
    current: '当前',
    actual: '实际',
    final: '最终',
    real: '真实',
    latest: '最新',
    recent: '最近',
    previous: '上一个',
    next: '下一个',
    first: '首个',
    last: '最后',
    existing: '现有',
    initial: '初始',
    new: '新',
    old: '旧',
    local: '本地',
    remote: '远程',
    active: '当前',
    visible: '可见',
    hidden: '隐藏',
    compact: '紧凑',
    separate: '单独',
    specific: '具体',
    generic: '通用',
    correct: '正确',
    stale: '过期',
    raw: '原始',
    native: '原生',
    automatic: '自动',
    automated: '自动',
    manual: '手动',
    successful: '成功',
    stable: '稳定',
    responsive: '响应式',
    relevant: '相关',
    remaining: '剩余',
    additional: '额外',
    known: '已知',
    unknown: '未知',
    missing: '缺失的',
    empty: '空',
    default: '默认',
    fallback: '兜底',
    full: '完整',
    common: '常见',
    technical: '技术',
    targeted: '定向',
    live: '实时',
    persistent: '常驻',
    temporary: '临时',
    completed: '已完成',
    failed: '失败',
    running: '运行中',
    pending: '等待中',
    project: '项目',
    repository: '仓库',
    code: '代码',
    source: '源代码',
    file: '文件',
    files: '文件',
    directory: '目录',
    directories: '目录',
    path: '路径',
    branch: '分支',
    commit: '提交',
    history: '历史',
    changes: '改动',
    change: '改动',
    state: '状态',
    status: '状态',
    data: '数据',
    metadata: '元数据',
    result: '结果',
    results: '结果',
    output: '输出',
    bundle: '资源包',
    bundles: '资源包',
    log: '日志',
    logs: '日志',
    error: '错误',
    errors: '错误',
    issue: '问题',
    issues: '问题',
    behavior: '行为',
    logic: '逻辑',
    implementation: '实现',
    engineering: '研发',
    component: '组件',
    components: '组件',
    page: '页面',
    view: '界面',
    screen: '页面',
    layout: '布局',
    style: '样式',
    styles: '样式',
    button: '按钮',
    buttons: '按钮',
    card: '卡片',
    text: '文字',
    copy: '文案',
    label: '文案',
    labels: '文案',
    title: '标题',
    titles: '标题',
    heading: '标题',
    headings: '标题',
    message: '消息',
    messages: '消息',
    summary: '摘要',
    phrase: '短语',
    phrases: '短语',
    word: '词汇',
    words: '词汇',
    identifier: '标识符',
    identifiers: '标识符',
    detail: '详情',
    details: '详情',
    inspection: '检查',
    progress: '进度',
    execution: '执行',
    plan: '计划',
    step: '步骤',
    steps: '步骤',
    phase: '阶段',
    action: '操作',
    operation: '操作',
    tool: '工具',
    tools: '工具',
    group: '分组',
    tab: '标签页',
    tabs: '标签页',
    session: '会话',
    conversation: '会话',
    thread: '会话',
    rollout: '执行记录',
    resume: '恢复',
    browser: '浏览器',
    mobile: '移动端',
    desktop: '桌面端',
    server: '服务器',
    service: '服务',
    network: '网络',
    connection: '连接',
    request: '请求',
    response: '响应',
    cache: '缓存',
    storage: '存储',
    preference: '偏好',
    preferences: '偏好',
    collapse: '收起',
    collapsed: '已收起',
    expand: '展开',
    expanded: '已展开',
    refresh: '刷新',
    refreshing: '刷新',
    reload: '刷新',
    reloading: '刷新',
    restarting: '重启',
    restart: '重启',
    persist: '持久化',
    persisted: '已持久化',
    persistence: '持久化',
    remember: '记住',
    remembered: '已记住',
    production: '生产环境',
    deployment: '部署',
    deploy: '部署',
    deploying: '部署',
    release: '发布',
    releasing: '发布',
    publish: '发布',
    publishing: '发布',
    sync: '同步',
    syncing: '同步',
    update: '更新',
    updates: '更新',
    updating: '更新',
    updated: '已更新',
    build: '构建',
    building: '构建',
    test: '测试',
    tests: '测试',
    testing: '测试',
    verification: '验收',
    validation: '验证',
    evaluation: '验收',
    command: '命令',
    commands: '命令',
    typecheck: '类型检查',
    check: '检查',
    checking: '检查',
    inspect: '检查',
    inspecting: '检查',
    review: '检查',
    reviewing: '检查',
    search: '搜索',
    searching: '搜索',
    read: '读取',
    reading: '读取',
    analyze: '分析',
    analyzing: '分析',
    evaluate: '评估',
    evaluating: '评估',
    verify: '验证',
    verifying: '验证',
    validate: '验证',
    validating: '验证',
    implement: '实现',
    implementing: '实现',
    add: '添加',
    adding: '添加',
    create: '创建',
    creating: '创建',
    edit: '修改',
    editing: '修改',
    modify: '修改',
    modifying: '修改',
    apply: '应用',
    applying: '应用',
    patch: '补丁',
    patching: '打补丁',
    fix: '修复',
    fixing: '修复',
    execute: '执行',
    executing: '执行',
    run: '运行',
    requesting: '请求',
    fetch: '获取',
    fetching: '获取',
    load: '加载',
    loading: '加载',
    use: '使用',
    using: '使用',
    translation: '翻译',
    translate: '翻译',
    translating: '翻译',
    localization: '中文化',
    localize: '中文化',
    localizing: '中文化',
    localized: '已中文化',
    coverage: '覆盖',
    english: '英文',
    chinese: '中文',
    user: '用户',
    experience: '体验',
    interface: '界面',
    ui: '界面',
    ux: '用户体验',
    visual: '视觉',
    screenshot: '截图',
    screenshots: '截图',
    size: '尺寸',
    canvas: '画布',
    mouse: '鼠标',
    event: '事件',
    events: '事件',
    dispatch: '分发',
    grid: '网格',
    child: '子项',
    children: '子项',
    index: '索引',
    indexing: '索引',
    authentication: '认证',
    flow: '流程',
    rules: '规则',
    worker: 'Worker',
}

const CHINESE_RE = /[\u3400-\u9fff]/
const CHINESE_ACTIVITY_PREFIX_RE = /^(正在[^：:]{1,12})[：:]\s*(.+)$/
const COMMAND_DETAIL_RE = /^(?:bun|npm|pnpm|yarn|git|curl|rsync|scp|ssh|pm2|node|deno|python\d*|pytest|vitest|jest|tsc|rg|grep|sed|awk|cat|find|make|docker)\b/i

function isCodeLikeWord(source: string, offset: number, length: number): boolean {
    const previous = source[offset - 1] ?? ''
    const next = source[offset + length] ?? ''
    return /[.:/\\_@#$-]/.test(previous) || /[.:/\\_@#$-]/.test(next)
}

function localizeActivityDetail(value: string): string {
    let localized = value.trim()
    if (COMMAND_DETAIL_RE.test(localized)) return localized
    for (const [pattern, replacement] of ACTIVITY_DETAIL_PHRASES_ZH) {
        localized = localized.replace(pattern, replacement)
    }
    localized = localized.replace(/\b[A-Za-z][A-Za-z'-]*\b/g, (word, offset: number) => {
        if (isCodeLikeWord(localized, offset, word.length)) return word
        return ACTIVITY_DETAIL_WORDS_ZH[word.toLowerCase()] ?? word
    })
    return localized
        .replace(/\s+/g, ' ')
        .replace(/([\u3400-\u9fff])\s+(?=[\u3400-\u9fff])/g, '$1')
        .replace(/\s+([，。；：！？])/g, '$1')
        .trim()
}

export function localizeCodexActivityTitle(value: string, locale: Locale): string {
    if (locale !== 'zh-CN') return value

    const localizedPrefix = value.match(CHINESE_ACTIVITY_PREFIX_RE)
    if (localizedPrefix) {
        return `${localizedPrefix[1]}：${localizeActivityDetail(localizedPrefix[2])}`
    }

    if (CHINESE_RE.test(value)) return localizeActivityDetail(value)
    for (const [pattern, prefix] of ACTIVITY_PREFIXES_ZH) {
        if (pattern.test(value)) {
            return `${prefix}${localizeActivityDetail(value.replace(pattern, ''))}`
        }
    }
    return `正在处理：${localizeActivityDetail(value)}`
}

export function isEnglishCodexActivityTitle(value: string, locale: Locale): boolean {
    return locale === 'zh-CN' && !CHINESE_RE.test(value)
}
